version: "3.5"

networks:
  ott-platform-net:
    name: ott-platform-net

volumes:
  redis-data:
  postgres-data:
  pgadmin-data:
  redisinsight-data:

services:
  redis:
    image: redis:6.2-alpine
    container_name: ott-redis
    command: redis-server --requirepass "ott_redis_pass"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - ott-platform-net

  redis-insight:
    image: redis/redisinsight:latest
    container_name: ott-redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    restart: unless-stopped
    networks:
      - ott-platform-net

  database:
    image: postgres:14-alpine
    container_name: ott-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ott_db_pass
      POSTGRES_DB: ott_platform_db
    restart: unless-stopped
    networks:
      - ott-platform-net

  pg-admin:
    image: dpage/pgadmin4
    container_name: ott-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ott-platform.com
      PGADMIN_DEFAULT_PASSWORD: ott_pg_pass
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5480:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database
    networks:
      - ott-platform-net

  user-backend:
    build:
      context: ../user-backend
      target: builder
    container_name: ott-user-backend
    command: npm run dev
    stdin_open: true
    tty: true
    volumes:
      - ../user-backend:/home/node/app
      - /home/node/app/node_modules 
    ports:
      - "8002:8002"
    env_file: ../user-backend/.env
    depends_on:
      - database
      - redis
    restart: unless-stopped
    networks:
      - ott-platform-net

  # admin-backend:
  #   build:
  #     context: ../admin-backend
  #     target: builder
  #   container_name: ott-admin-backend
  #   command: npm run dev
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ../admin-backend:/home/node/app
  #     - /home/node/app/node_modules 
  #   ports:
  #     - "8003:8003"
  #   env_file: ../admin-backend/.env
  #   depends_on:
  #     - database
  #     - redis
  #   restart: unless-stopped
  #   networks:
  #     - ott-platform-net
